print("Hello, world!")
print("What is your name? ")
yourName = input()
print("it's good to meet you, " + yourName.upper())
print("the length of your name is: " + str(len(yourName)))
print("what is your age? ")
age = input()
print("You will be " + str(int(age) + 1) + " in a year. ")
